import { Vector3 } from '@babylonjs/core'

export const STATIC_LIGHT_FADE_SECONDS = 0.25
export const STATIC_LIGHT_DEFAULT_BRIGHTNESS_FACTOR = 0.25 + (4 / 9)
export const STATIC_LIGHT_LIMITS = [4, 6, 6]
export const OUTDOOR_STATIC_LIGHT_LIMITS = [1, 2, 2]
export const ACTOR_STATIC_LIGHT_LIMIT = 4
export const OUTDOOR_ACTOR_STATIC_LIGHT_LIMIT = 2
export const STATIC_SHADOW_MAP_SIZE = 1024
export const LARGE_CAMPFIRE_SHADOW_MAP_SIZE = 2048
export const LARGE_CAMPFIRE_SHADOW_SLOT_COUNT = 2
export const FILTER_ACTOR_STATIC_SHADOW_CASTERS_BY_DISTANCE = true
export const ACTOR_STATIC_SHADOW_CASTER_UPDATE_SECONDS = 0.1
export const STATIC_FIRE_SMOKE_PARTICLE_FACTORS = [0.4, 0.65, 1]

export const PERSONAL_LIGHT_X_OFFSET = -0.35
export const PERSONAL_LIGHT_Z_OFFSET = -0.35
export const INDOOR_PERSONAL_LIGHT_HEIGHT = 2.5
export const OUTDOOR_PERSONAL_LIGHT_HEIGHT = 3.5
export const INDOOR_PERSONAL_SHADOW_DARKNESS = 0.15
export const OUTDOOR_PERSONAL_SHADOW_DARKNESS = 0.25
export const PERSONAL_LIGHT_POSITION = new Vector3(PERSONAL_LIGHT_X_OFFSET, OUTDOOR_PERSONAL_LIGHT_HEIGHT, PERSONAL_LIGHT_Z_OFFSET)
export const PERSONAL_LIGHT_DIRECTION = new Vector3(0.25, -2.5, 0.25).normalize()

export const INITIAL_DAY_NIGHT_PHASE = 1 / 3
export const DEFAULT_DAY_NIGHT_CYCLE_DURATION_MS = 60 * 60 * 1000
export const DEFAULT_ENVIRONMENT_INTENSITY = 0.375
export const NIGHT_ENVIRONMENT_INTENSITY_FACTOR = 0.05
export const OUTDOOR_STATIC_LIGHT_INTENSITY_FACTOR = 1.4
export const OUTDOOR_STATIC_LIGHT_RANGE_FACTOR = 1.5
